{% extends '//die/gen.sh' %}

{# The lab's private CA: lab_proxy on lab1-3 serves <name>.lab.mesh with
   leaves it issues. Generated by lab's gen_lab_ca, published at
   http://labN.mesh/ca.crt; concat folds it into /etc/ssl/cert.pem. #}

{% block install %}
mkdir -p ${out}/etc/ssl/cert.pem.d

cat << 'EOF' > ${out}/etc/ssl/cert.pem.d/lab.pem
-----BEGIN CERTIFICATE-----
MIIBcTCCARagAwIBAgIUX4vKsU3ndiLwE8RXjzXK00/I4SMwCgYIKoZIzj0EAwIw
FjEUMBIGA1UEAwwLbGFiLm1lc2ggQ0EwHhcNMjYwOTIxMTEzNDIyWhcNNDYwOTE2
MTEzNDIyWjAWMRQwEgYDVQQDDAtsYWIubWVzaCBDQTBZMBMGByqGSM49AgEGCCqG
SM49AwEHA0IABCadf7wrYEj/ICzjUfIgg1AP9wd9v0CtFu5SzepEYqFDHxg8PGZe
X4ersxMCuMPBTlCvKtRLFQ1BJFUhExP4m8ajQjBAMA8GA1UdEwEB/wQFMAMBAf8w
DgYDVR0PAQH/BAQDAgEGMB0GA1UdDgQWBBSdVUYvdPb6xpPeZS2eUqs4kaU6NDAK
BggqhkjOPQQDAgNJADBGAiEA/ZZEdEdp/BKHon09qoaYSRfcsvesyGkBDbcfvy5A
my4CIQDRMGRdSlEOSbgeBNfi+WdLZpAV00kZUGiQ4j4U+Ms35g==
-----END CERTIFICATE-----

EOF
{% endblock %}
